#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          webuzo
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Should-Start:      $network $time
# Should-Stop:       $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Webuzo is a Control Panel.
# Description:       Webuzo is a LAMP Stack and a Single User Control Panel which helps you deploy Apps on your server. "webuzo".
### END INIT INFO
# (c) Softaculous Ltd.
# Service for EMPS (WEBUZO)
#
# chkconfig: 2345 99 90
# description: Webuzo is a LAMP Stack and a Single User Control Panel \
# which helps you deploy Apps on your server, \
# virtual machine or in the cloud.
#
# processname: webuzo
# config: /usr/local/emps/etc
#
RETVAL=0
# See how we were called.
case "$1" in
  start)
	# Create a hardlink for the Webuzo Service file
	if [ -f /usr/bin/systemctl ] || [ -f /bin/systemctl ] ; then
		if [ ! -f /etc/systemd/system/webuzo.service ] ; then
		
			echo "Creating webuzo.service file for systemd"
			echo "Creating webuzo.service file for systemd" > /var/webuzo/service
			ln /usr/local/webuzo/conf/webuzo/emps/webuzo.service /etc/systemd/system/webuzo.service
			
			# Enable the service as well
			systemctl enable webuzo
			
		fi
	fi
  
	/usr/local/emps/bin/fpmctl start
	/usr/local/emps/bin/nginxctl start
	
	# Do a service check
	/usr/local/emps/bin/php /usr/local/webuzo/service_check.php >> /var/webuzo/service 2>&1 &
	
	echo "DONE ! Starting services" >> /var/webuzo/service
	;;
  stop)
  
	/usr/local/emps/bin/fpmctl stop
	/usr/local/emps/bin/nginxctl stop
	;;
  status)
  
	/usr/local/emps/bin/fpmctl status
	/usr/local/emps/bin/nginxctl status
	;;
  restart|reload)
    cd "$CWD"
	$0 stop
	$0 start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|status}"
	RETVAL=2
esac

exit $RETVAL
